version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: paddlebook_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: paddle
      POSTGRES_PASSWORD: paddle
      POSTGRES_DB: paddlebook
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
